/*
EECS 348 Assignment 1 - granite.c

Description: Number guessing game where the user guesses a fixed secret
number between 1 and 10, with up to 3 guesses. This is the output of
Model 2 in the GenAI comparison (see genai-analysis.md), with one minimal
fix applied so it compiles.

Inputs: None (interactive guesses are read via scanf, not passed as
program arguments).

Output (intended, per the prompt below; note the code review in
genai-analysis.md found the "Game over" message never actually prints
because attempt no longer equals attempts_allowed once the for loop's own
increment runs after the last failed guess):
 >   Guess a number between 1 and 10.
 >   Attempt 1/3. Enter your guess: 5
 >   Too low! Try again.
 >   Attempt 2/3. Enter your guess: 8
 >   Too high! Try again.
 >   Attempt 3/3. Enter your guess: 7
 >   Correct! You win!

Collaborators: None

Other sources: Program generated by a local Ibm Granite_Granite 4.2 3b LLM
run through LM Studio (https://lmstudio.ai); see genai-analysis.md for the
prompt and the full code review.
Prompt:
    "Write a C program that picks a secret number between 1 and 10. The user gets up to 3 tries to guess the number.
    The secret number should be fixed. Printf and Scanf should be used to interact with the user. A while or for loop should be used to allow
    the user to guess up to three times. Use if/else statements to check the guess. Stop the loop immediately if the user guesses correctly.
    Print a final win/lose message. Make sure the program follows this output scheme:
        >   Guess a number between 1 and 10.
        >   Attempt 1/3. Enter your guess: 5
        >   Too low! Try again.
        >   Attempt 2/3. Enter your guess: 8
        >   Too high! Try again.
        >   Attempt 3/3. Enter your guess: 7
        >   Correct! You win!"

Author: David Joslin, KUID 3218103
Created: Sept. 8, 2026
Revision date: Sept. 8, 2026
Revisions: Fixed an invalid printf() call (called with no arguments,
which fails to compile) to printf(""); no other edits, so the logic bugs
noted in the code review are left intact.
*/

#include <stdio.h>
#include <stdlib.h>

int main() {
    int secret = 7; // Fixed secret number (from your example output)
    int attempts_allowed = 3;
    int guess, attempt;

    printf("Guess a number between 1 and 10.\n");
    
    for (attempt = 1; attempt <= attempts_allowed; ++attempt) {
        printf("\nAttempt %d/%d. Enter your guess: ", attempt, attempts_allowed);
        
        // Read user input
        if (scanf("%d", &guess) != 1) {
            printf("Invalid input.\n");
            return EXIT_FAILURE;
        }

        printf(""); // Clear the line after number entry
        
        if (guess == secret) {
            printf("Correct! You win!\n");
            break;
        } else if (guess < secret) {
            printf("Too low! Try again.\n");
        } else {
            printf("Too high! Try again.\n");
        }
    }

    // If we finish the loop without breaking (user ran out of attempts)
    if (attempt == attempts_allowed && guess != secret) {
        printf("You've used all your attempts. Game over!\n");
    }

    return EXIT_SUCCESS;
}