/*
EECS 348 Assignment 1 - liquid.c

Description: Number guessing game where the user guesses a fixed secret
number between 1 and 10, with up to 3 guesses. This is the raw, unedited
output of Model 1 in the GenAI comparison (see genai-analysis.md).

Inputs: None (interactive guesses are read via scanf, not passed as
program arguments).

Output:
 >   Guess a number between 1 and 10.
 >   Attempt 1/3. Enter your guess: 5
 >   Too low! Try again.
 >   Attempt 2/3. Enter your guess: 8
 >   Too high! Try again.
 >   Attempt 3/3. Enter your guess: 7
 >   Correct! You win!

Collaborators: None

Other sources: Entire program generated by a local liquid/lfm2.5-1.2b LLM
run through LM Studio (https://lmstudio.ai); see genai-analysis.md for the
prompt, the full code review, and how this output was used to inform
main.c. Not hand-edited.
Prompt:
    "Write a C program that picks a secret number between 1 and 10. The user gets up to 3 tries to guess the number.
    The secret number should be fixed. Printf and Scanf should be used to interact with the user. A while or for loop should be used to allow
    the user to guess up to three times. Use if/else statements to check the guess. Stop the loop immediately if the user guesses correctly.
    Print a final win/lose message. Make sure the program follows this output scheme:
        >   Guess a number between 1 and 10.
        >   Attempt 1/3. Enter your guess: 5
        >   Too low! Try again.
        >   Attempt 2/3. Enter your guess: 8
        >   Too high! Try again.
        >   Attempt 3/3. Enter your guess: 7
        >   Correct! You win!"

Author: David Joslin, KUID 3218103
Created: Sept. 8, 2026
Revision date: Sept. 8, 2026
Revisions: None; kept as raw LLM output for comparison against granite.c.
*/


#include <stdio.h>

int main() {
    int secret = 5; // Fixed secret number between 1 and 10
    int attempts = 0;
    int guess;

    printf("Guess a number between 1 and 10.\n");
    while (attempts < 3) {
        printf("Attempt %d/3. Enter your guess: ", attempts + 1);
        scanf("%d", &guess);

        if (guess < secret) {
            printf("Too low! Try again.\n");
        } else if (guess > secret) {
            printf("Too high! Try again.\n");
        } else {
            printf("Correct! You win!\n");
            return 0;
        }
        attempts++;
    }

    printf("Game over. The secret number was %d.\n", secret);
    return 0;
}