/*
EECS 348 Assignment 1 - main.c

Description: Number guessing game where the user guesses a fixed secret
number between 1 and 10, with up to 3 guesses.

Inputs: None (interactive guesses are read via scanf, not passed as
program arguments).

Output:
 >   Guess a number between 1 and 10.
 >   Attempt 1/3. Enter your guess: 5
 >   Too low! Try again.
 >   Attempt 2/3. Enter your guess: 8
 >   Too high! Try again.
 >   Attempt 3/3. Enter your guess: 7
 >   Correct! You win!

Collaborators: None

Other sources: This program was generated by a local liquid/lfm2.5-1.2b LLM
(see liquid.c for the raw, unedited output), chosen over an Ibm
Granite_Granite 4.2 3b generated program (see granite.c) per the analysis
in genai-analysis.md: it compiled and ran without edits and had no logic
bugs, while the granite version failed to compile initially and never
printed its game-over message.
Prompt:
    "Write a C program that picks a secret number between 1 and 10. The user gets up to 3 tries to guess the number.
    The secret number should be fixed. Printf and Scanf should be used to interact with the user. A while or for loop should be used to allow
    the user to guess up to three times. Use if/else statements to check the guess. Stop the loop immediately if the user guesses correctly.
    Print a final win/lose message. Make sure the program follows this output scheme:
        >   Guess a number between 1 and 10.
        >   Attempt 1/3. Enter your guess: 5
        >   Too low! Try again.
        >   Attempt 2/3. Enter your guess: 8
        >   Too high! Try again.
        >   Attempt 3/3. Enter your guess: 7
        >   Correct! You win!"

Author: David Joslin, KUID 3218103
Created: Sept. 8, 2026
Revision date: Sept. 8, 2026
Revisions: Added a line comment to every statement explaining its purpose
(logic unchanged from the liquid.c LLM output).
*/


#include <stdio.h> // Needed for printf/scanf

int main() { // Entry point, begin main function
    int secret = 5; // Fixed secret number between 1 and 10
    int attempts = 0; // Number of guesses made so far
    int guess; // Stores the user's current guess

    printf("Guess a number between 1 and 10.\n"); // Prompt shown once before guessing begins
    while (attempts < 3) { // Allow up to 3 guesses total
        printf("Attempt %d/3. Enter your guess: ", attempts + 1); // Show current attempt number, starting at 1
        scanf("%d", &guess); // Read the user's guess into guess

        if (guess < secret) { // Guess is below the secret number
            printf("Too low! Try again.\n"); // Tell the user to guess higher
        } else if (guess > secret) { // Guess is above the secret number
            printf("Too high! Try again.\n"); // Tell the user to guess lower
        } else { // Guess matches the secret number
            printf("Correct! You win!\n"); // Announce the win
            return 0; // Exit immediately so the loop stops and no lose message prints
        }
        attempts++; // Count this attempt before looping again
    }

    printf("Game over. The secret number was %d.\n", secret); // Reached only if all 3 guesses were wrong
    return 0; // Normal exit after a loss
} // End main function
